# Generated by Django 6.0.7 on 2026-07-31 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('uy', 'Uy hayvonlari'), ('yovvoyi', 'Yovvoyi hayvonlar'), ('qushlar', 'Qushlar'), ('suv', 'Suv hayvonlari'), ('hasharot', 'Hasharotlar')], default='uy', max_length=20, verbose_name='Turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/categories/', verbose_name='Kategoriya rasmi')),
                ('icon', models.CharField(blank=True, help_text='Masalan: 🐶, 🦁', max_length=50, verbose_name='Emoji/Icon')),
                ('color', models.CharField(default='#FFE66D', max_length=20, verbose_name='Fon rangi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Hayvon kategoriyasi',
                'verbose_name_plural': 'Hayvon kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Qizil', max_length=50, verbose_name='Rang nomi')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Inglizcha nomi')),
                ('hex_code', models.CharField(default='#FF0000', help_text='#FF0000', max_length=20, verbose_name='HEX kodi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='Rang rasmi (obyekt)')),
                ('audio', models.FileField(blank=True, null=True, upload_to='colors/audios/', verbose_name='Rang talaffuzi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Salomlashish', max_length=150, verbose_name='Mavzu nomi')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mavzu tavsifi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conversation/topics/', verbose_name='Mavzu rasmi')),
                ('icon', models.CharField(blank=True, help_text='Masalan: 👋', max_length=50, verbose_name='Icon/Emoji')),
                ('color', models.CharField(default='#A8E6CF', max_length=20, verbose_name='Fon rangi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "So'zlashuv mavzusi",
                'verbose_name_plural': "So'zlashuv mavzulari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(help_text='Masalan: A, B, D...', max_length=5, verbose_name='Harf')),
                ('name', models.CharField(help_text='Masalan: A harfi', max_length=100, verbose_name='Harf nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='letters/images/', verbose_name='Harf rasmi')),
                ('audio', models.FileField(blank=True, help_text='MP3, WAV', null=True, upload_to='letters/audios/', verbose_name='Harf talaffuzi (ovoz)')),
                ('example_word', models.CharField(blank=True, help_text='Masalan: Olma', max_length=100, verbose_name="Misoldagi so'z")),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='letters/examples/', verbose_name='Misol rasmi')),
                ('example_audio', models.FileField(blank=True, null=True, upload_to='letters/examples/audio/', verbose_name="Misol so'z ovozi")),
                ('description', models.TextField(blank=True, help_text='Bolalar uchun harf haqida', verbose_name='Qisqacha tavsif')),
                ('color', models.CharField(default='#FF6B6B', help_text='Masalan: #FF6B6B', max_length=20, verbose_name='Fon rangi (HEX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Harf',
                'verbose_name_plural': 'Harflar',
                'ordering': ['order', 'char'],
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Masalan: 1, 2, 3...', unique=True, verbose_name='Raqam qiymati')),
                ('word', models.CharField(help_text='Masalan: bir, ikki', max_length=100, verbose_name="So'z bilan")),
                ('image', models.ImageField(blank=True, null=True, upload_to='numbers/images/', verbose_name='Raqam rasmi')),
                ('audio', models.FileField(blank=True, null=True, upload_to='numbers/audios/', verbose_name='Raqam talaffuzi')),
                ('count_image', models.ImageField(blank=True, null=True, upload_to='numbers/count/', verbose_name='Miqdor rasmi (masalan 3 ta olma)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('color', models.CharField(default='#4ECDC4', max_length=20, verbose_name='Fon rangi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Raqam',
                'verbose_name_plural': 'Raqamlar',
                'ordering': ['order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Mushuk', max_length=100, verbose_name='Hayvon nomi')),
                ('name_en', models.CharField(blank=True, help_text='Masalan: Cat', max_length=100, verbose_name='Inglizcha nomi')),
                ('image', models.ImageField(upload_to='animals/images/', verbose_name='Hayvon rasmi')),
                ('audio_sound', models.FileField(blank=True, null=True, upload_to='animals/sounds/', verbose_name='Hayvon ovozi (miyov, vov...) ')),
                ('audio_name', models.FileField(blank=True, null=True, upload_to='animals/names/', verbose_name='Nom talaffuzi ovozi')),
                ('description', models.TextField(blank=True, verbose_name='Hayvon haqida (bolalar uchun)')),
                ('where_lives', models.CharField(blank=True, max_length=200, verbose_name='Qayerda yashaydi?')),
                ('what_eats', models.CharField(blank=True, max_length=200, verbose_name='Nima yeydi?')),
                ('interesting_fact', models.TextField(blank=True, verbose_name='Qiziqarli fakt')),
                ('color', models.CharField(default='#FF9F1C', max_length=20, verbose_name='Fon rangi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='core.animalcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Hayvon',
                'verbose_name_plural': 'Hayvonlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Mashq nomi')),
                ('type', models.CharField(choices=[('match', 'Moslashtirish (rasm-soz)'), ('listen', 'Eshit va top'), ('speak', 'Qaytarib ayt'), ('puzzle', 'Jumboq')], default='listen', max_length=20, verbose_name='Mashq turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Rasm')),
                ('audio', models.FileField(blank=True, null=True, upload_to='exercises/audios/', verbose_name='Ovoz')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('related_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.animal', verbose_name="Bog'liq hayvon")),
                ('related_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.letter', verbose_name="Bog'liq harf")),
                ('related_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.number', verbose_name="Bog'liq raqam")),
            ],
            options={
                'verbose_name': "Mashq / O'yin",
                'verbose_name_plural': "Mashqlar / O'yinlar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Masalan: Salom, qanday ahvoldasan?', max_length=300, verbose_name="Ibora / So'z")),
                ('translation', models.CharField(blank=True, help_text='Bolalar uchun tushuntirish', max_length=300, verbose_name='Tarjimasi / Izohi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conversation/phrases/', verbose_name='Rasm')),
                ('audio', models.FileField(blank=True, null=True, upload_to='conversation/audios/', verbose_name='Ovozli talaffuz')),
                ('example', models.TextField(blank=True, verbose_name='Misol gap')),
                ('difficulty', models.CharField(choices=[('oson', 'Oson'), ('orta', "O'rtacha"), ('qiyin', 'Qiyin')], default='oson', max_length=10, verbose_name='Qiyinlik darajasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='core.conversationtopic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': "So'zlashuv iborasi",
                'verbose_name_plural': "So'zlashuv iboralari",
                'ordering': ['order'],
            },
        ),
    ]
